# spacecowboy — generated by ~/dotfiles/theme/render.py; do not edit
# exec'd by ~/.ipython/profile_default/ipython_config.py with `c` in scope.
from pygments.token import Token

try:
    c  # noqa: B018  (defined by the config file that execs us)
except NameError:  # run standalone: nothing to do
    c = get_config()  # noqa: F821

c.TerminalInteractiveShell.true_color = True
c.TerminalInteractiveShell.highlighting_style_overrides = {
    Token.Comment: "italic #7a6852",
    Token.Comment.Single: "italic #7a6852",
    Token.Keyword: "#a8d88a",
    Token.Keyword.Constant: "#f3e9d6",
    Token.Keyword.Namespace: "#6f8f3a",
    Token.Keyword.Type: "#f3e9d6",
    Token.Name: "#d3c6b0",
    Token.Name.Builtin: "#e59a5b",
    Token.Name.Builtin.Pseudo: "italic #f3e9d6",
    Token.Name.Class: "#f3e9d6",
    Token.Name.Decorator: "#a8d88a",
    Token.Name.Exception: "#f3e9d6",
    Token.Name.Function: "bold #e59a5b",
    Token.Name.Namespace: "#a99a85",
    Token.Name.Variable: "#d3c6b0",
    Token.Literal.String: "#bfb29c",
    Token.Literal.String.Doc: "italic #7a6852",
    Token.Literal.String.Escape: "#d3c6b0",
    Token.Literal.Number: "#e6b98c",
    Token.Operator: "#d3c6b0",
    Token.Operator.Word: "#a8d88a",
    Token.Punctuation: "#a99a85",
    Token.Error: "#e07a5f",
    Token.Prompt: "#b7d9a0",
    Token.PromptNum: "bold #b7d9a0",
    Token.OutPrompt: "#d3c6b0",
    Token.OutPromptNum: "bold #d3c6b0",
}
