-- spacecowboy — generated by ~/dotfiles/theme/render.py; do not edit
-- Overlay for awesome's theme.lua: it does
--   local ok, t = pcall(dofile, os.getenv("HOME") .. "/.config/theme/current/awesome.lua")
--   if ok and type(t) == "table" then for k, v in pairs(t) do theme[k] = v end end
-- right before `return theme`, so every key here wins over the file's own.
return {
  bg_normal     = "#201812",
  bg_focus      = "#362a20",
  bg_urgent     = "#e07a5f",
  bg_minimize   = "#43352a",
  bg_systray    = "#201812",

  fg_normal     = "#d3c6b0",
  fg_focus      = "#f3e9d6",
  fg_urgent     = "#201812",
  fg_minimize   = "#7a6852",

  border_normal = "#d3c6b0",
  border_focus  = "#b7d9a0",
  border_marked = "#e07a5f",

  taglist_bg_focus    = "#a8d88a",
  taglist_fg_focus    = "#201812",
  taglist_bg_urgent   = "#e07a5f",
  taglist_fg_urgent   = "#201812",
  taglist_bg_occupied = "#2a2019",
  taglist_fg_occupied = "#d3c6b0",
  taglist_fg_empty    = "#7a6852",

  tasklist_bg_focus   = "#362a20",
  tasklist_fg_focus   = "#f3e9d6",
  tasklist_bg_urgent  = "#e07a5f",
  tasklist_fg_urgent  = "#201812",

  titlebar_bg_normal  = "#201812",
  titlebar_bg_focus   = "#2a2019",
  titlebar_fg_normal  = "#7a6852",
  titlebar_fg_focus   = "#d3c6b0",

  tooltip_bg          = "#201812",
  tooltip_fg          = "#d3c6b0",
  tooltip_border_color = "#8a6a52",

  notification_bg     = "#201812",
  notification_fg     = "#d3c6b0",
  notification_border_color = "#8a6a52",

  menu_bg_normal      = "#201812",
  menu_bg_focus       = "#362a20",
  menu_fg_normal      = "#d3c6b0",
  menu_fg_focus       = "#f3e9d6",
  menu_border_color   = "#8a6a52",

  prompt_bg           = "#201812",
  prompt_fg           = "#a8d88a",
  prompt_fg_cursor    = "#201812",
  prompt_bg_cursor    = "#e59a5b",
}
